[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/restaurantbackend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
SPRING_PROFILES_ACTIVE = "prod"
