CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    icon_name VARCHAR(255),
    color_code VARCHAR(7),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0
);

-- Insert some default departments
INSERT INTO departments (name, description, icon_name, color_code, sort_order) VALUES
('Mutfak', 'Ana yemeklerin hazırlandığı bölüm', 'HomeOutlined', '#FF5733', 10),
('Bar', 'İçeceklerin hazırlandığı bölüm', 'CoffeeOutlined', '#3366FF', 20),
('Dondurma', 'Dondurma ve soğuk tatlılar', 'StarOutlined', '#FFC300', 30),
('Salata', 'Salata ve hafif başlangıçlar', 'AppleOutlined', '#33FF57', 40),
('Tatlı', 'Sıcak tatlılar ve pastalar', 'CrownOutlined', '#8A2BE2', 50),
('Genel', 'Diğer ürünler', 'ShopOutlined', '#607D8B', 99);
